name: Build
on: [push]
jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: make
      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: security-add-trusted-cert
          path: |
            security-add-trusted-cert
