name: Build
on: [push]
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          make APP_VERSION="$GITHUB_REF_NAME"
          mv security-add-trusted-cert security-add-trusted-cert-amd64
      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: security-add-trusted-cert-amd64
          path: |
            security-add-trusted-cert-amd64
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-22.04
    needs:
      - build
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          artifacts: 'security-add-trusted-cert-amd64/security-add-trusted-cert-amd64'
